// Generates texas/data.js from the source CSV files.
// Usage (from repo root): node texas/build-data.js

const fs   = require('fs');
const path = require('path');

const CSV_PATH   = path.join(__dirname, 'fake_texas_data_v2.csv');
const NAMES_PATH = path.join(__dirname, 'district_names.csv');
const OUT_PATH   = path.join(__dirname, 'data.js');

// Parse a CSV file into an array of row objects
function parseCSV(filePath) {
  const lines   = fs.readFileSync(filePath, 'utf8').trim().split('\n');
  const headers = lines[0].split(',');
  return lines.slice(1).map(line => {
    const cols = line.split(',');
    const obj  = {};
    headers.forEach((h, i) => { obj[h] = cols[i]; });
    return obj;
  });
}

const rows     = parseCSV(CSV_PATH);
const nameRows = parseCSV(NAMES_PATH);

// Build code → name map
const nameMap = {};
nameRows.forEach(r => { nameMap[r['DIST_CODE']] = r['DISTRICT_NAME']; });

const parse = v => v === 'NA' ? null : parseInt(v, 10);
const jv    = v => v === null ? 'null' : v;

const SUBJECTS = [
  'Reading',
  'Writing',
  'Health',
  'Mathematics',
];

// Collect all district codes in sorted order (only those with a name entry)
const allCodes = [...new Set(rows.map(r => r['DIST_CODE']))]
  .filter(c => nameMap[c])
  .sort();

// Build district data
const districts = {};
for (const code of allCodes) {
  const key = `d${code}`;
  districts[key] = { label: nameMap[code], subjects: {} };
  for (const subj of SUBJECTS) {
    districts[key].subjects[subj] = rows
      .filter(r => r['DIST_CODE'] === code &&
                   r['DATA_CATEGORY_GROUP'] === 'Race/Ethnicity' &&
                   r['ASSESSMENT SUBJECT'] === subj)
      .map(r => ({
        group: r['DATA_CATEGORY'],
        conf:  { enrolled: parse(r['ECDS_REPORTED']),          assessed: parse(r['BOTH_BOY_EOY_ASSESSED']),          proficient: parse(r['MATCH_PROFICIENT_EOY'])          },
        supp:  { enrolled: parse(r['ECDS_REPORTED_suppress']), assessed: parse(r['BOTH_BOY_EOY_ASSESSED_suppress']), proficient: parse(r['MATCH_PROFICIENT_EOY_suppress']) },
        noisy: { enrolled: parse(r['ECDS_REPORTED_noisy_pp']), assessed: parse(r['BOTH_BOY_EOY_ASSESSED_noisy_pp']), proficient: parse(r['MATCH_PROFICIENT_EOY_noisy_pp']) },
      }));
  }
}

// Emit data.js
let out = `window.SD = window.SD || {};

SD.txData = (function () {

  const SUBJECTS = [
${SUBJECTS.map(s => `    '${s}'`).join(',\n')},
  ];

  // Generated by texas/build-data.js — do not edit by hand.
  // Source: fake_texas_data.csv + district_names.csv
  // Race/Ethnicity rows only. District codes replaced with pseudo names.
  // null = suppressed (NA) in that release version.
  const districts = {
`;

for (const [dk, dv] of Object.entries(districts)) {
  out += `    ${dk}: {\n      label: '${dv.label}',\n      subjects: {\n`;
  for (const subj of SUBJECTS) {
    out += `        '${subj}': [\n`;
    for (const r of dv.subjects[subj]) {
      out += `          { group: '${r.group}', conf: { enrolled: ${jv(r.conf.enrolled)}, assessed: ${jv(r.conf.assessed)}, proficient: ${jv(r.conf.proficient)} }, supp: { enrolled: ${jv(r.supp.enrolled)}, assessed: ${jv(r.supp.assessed)}, proficient: ${jv(r.supp.proficient)} }, noisy: { enrolled: ${jv(r.noisy.enrolled)}, assessed: ${jv(r.noisy.assessed)}, proficient: ${jv(r.noisy.proficient)} } },\n`;
    }
    out += `        ],\n`;
  }
  out += `      },\n    },\n`;
}

out += `  };

  return { districts, SUBJECTS };
})();
`;

fs.writeFileSync(OUT_PATH, out);
console.log(`Written ${OUT_PATH} — ${allCodes.length} districts`);
